# Generated by Django 5.2.5 on 2025-08-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvert',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobadvert',
            name='job_type',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobadvert',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
